name: Unit Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install ExifTool
      run: |
        sudo apt-get update
        sudo apt-get install -y exiftool

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Verify ExifTool installation
      run: |
        exiftool -ver
        which exiftool

    - name: Run comprehensive test suite
      run: |
        python -m pytest test_takeout_processor.py -v